enableGlobalCache: true

httpProxy: "http://127.0.0.1:1080"

httpsProxy: "http://127.0.0.1:1080"

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
